### ISSUE TITLE
针对我

### ISSUE THREAD

**Issue by 212721** [codehub666/94list#10]
好吧，搞了一天，我发现个事，不论是安装，访问，只要我不是无痕他就会无法安装，即不可视化，访问也是一样，我以为是bug，别人没事，我换了共3台手机与电脑，就是针对我，开无痕没事，不知道什么原因，好神奇，麻烦作者以后不要创造生灵了，放在地球是违神法的，懂，以后别创作生灵了，太调皮了，最后除了针对我，一切很好，大概吧。。。没试过，刚刚好

**Comment by 212721** [comment]
顺便问下，怎么评分

**Comment by codehub666** [comment]
代码是死滴，事出反常必有妖
