### ISSUE TITLE
不能连接数据库，内含教程方法【已解决】

### ISSUE THREAD

**Issue by Aqr-K** [codehub666/94list#15]
用docker部署的，mysql:5.7是另一个的容器，这个项目的容器底层系统是debian:bullseye，手动安装了curl、git、wget、php、php-curl、php-mysql、apache2，php是7.4，用apache2启动，项目直接下载在了/var/www/html

不管加不加http都无法启动，端口账号密码无错
![image](https://github.com/codehub666/94list/assets/95741669/c892ad9f-820d-4b97-95c0-23c166eda60c)
![image](https://github.com/codehub666/94list/assets/95741669/b2113dbf-3d0d-4c9d-98d2-20621e353e60)
![image](https://github.com/codehub666/94list/assets/95741669/7fb91230-0957-45e5-98cf-5692d8c40c22)
![image](https://github.com/codehub666/94list/assets/95741669/a837763f-9ea4-4d64-b234-cc39df9deba7)

请问是哪里操作错了吗？

**Comment by xzw2938013811** [comment]
项目中的api.php文件补全<?php  .... ?>  试试

**Comment by Aqr-K** [comment]
> 项目中的api.php文件补全 试试

不是很懂你说的意思，是缺什么了啊？

**Comment by xzw2938013811** [comment]
![image](https://github.com/codehub666/94list/assets/91815896/2747b38a-5da3-4001-9bce-b1ca1e3fdfb4)

**Comment by Aqr-K** [comment]
这个方法是可行的，现在反馈信息了，如果显示无权限写入的话，给项目的根目录文件夹做个赋权一下就行了，命令是`chmod +x 你的根目录`

**Comment by codehub666** [comment]
已修正不规范的PHP写法
