### ISSUE TITLE
请教未知错误代码-9是哪方面的问题？

### ISSUE THREAD

**Issue by LucasStudioLeo** [codehub666/94list#16]
![image](https://github.com/codehub666/94list/assets/100138795/456a543d-4141-4216-b804-416af587d0ff)

**Comment by codehub666** [comment]
-9报错还没遇到过，有结果麻烦帮忙反馈一下。

**Comment by yuantuo666** [comment]
文件不存在，可能是获取下载连接被检测到是违规文件封禁了，参见 https://github.com/yuantuo666/baiduwp-php/blob/0db571641d868d72444b1de387a194b75c45646b/app/Parse.php#L408

**Comment by LucasStudioLeo** [comment]
好的谢谢提醒
