### ISSUE TITLE
初次连接数据库后，admin异常【已解决】

### ISSUE THREAD

**Issue by Aqr-K** [codehub666/94list#17]
初次连接数据库后，发现不会优先跳转到admin目录下的login.php进行登录，是直接进入了index.php，但其实是没有权限的，所有功能交互显示也是无反馈的，我是扒了一下项目的文件路径，才能手动进入login.php登录
能不能加个判定啊

**Comment by codehub666** [comment]
/admin/index.php文件下
    if (!if_login()) {
        header('Location: ./login.php');
    }
   有判断登录跳转的。是不是你修改过什么？

**Comment by codehub666** [comment]
/admin/index.php文件下
 if (if_login()) {
        header('Location: ./');
    }
有判断是否登录进行跳转的。不是你修改过什么？
数据库配置文件:config.php有生成在根目录下吗？

**Comment by Aqr-K** [comment]
> /admin/index.php文件下 if (if_login()) { header('Location: ./'); } 有判断是否登录进行跳转的。不是你修改过什么？ 数据库配置文件:config.php有生成在根目录下吗？

config.php文件确实生成了
我好像找到原因了，我扒了一下代码，发现是你原来的admin的php格式不规范，我是几天前做成了镜像，所以源码没更新到上次提到的规范问题

**Comment by codehub666** [comment]
> > /admin/index.php文件下 if (if_login()) { header('位置: ./'); 数据库配置文件:config.php有生成在根目录下吗？
> 
> config.php文件确实生成了 我想要找到原因了，我抓取了图片代码，发现是你原来的admin的php格式不规范，我是几天前完成了类似的，所以源码没有更新到前面提到的的规范问题

对，代码没封闭导致<?php ...... ?>，一些环境没办法自动读取，包裹起来就没事了，我也有进行更新。

**Comment by codehub666** [comment]
> > /admin/index.php文件下 if (if_login()) { header('位置: ./'); 数据库配置文件:config.php有生成在根目录下吗？
> 
> config.php文件确实生成了 我想要找到原因了，我抓取了图片代码，发现是你原来的admin的php格式不规范，我是几天前完成了类似的，所以源码没有更新到前面提到的的规范问题

是的，代码没做封闭导致：<?php ....?>。疏忽其他环境没办法自动识别代码。后面代码我也已做修整。
