### ISSUE TITLE
本地部署之后，后台cookie怎么获取，是在哪获取，求解答【已解决】

### ISSUE THREAD

**Issue by w14797034489** [codehub666/94list#19]

**Comment by codehub666** [comment]
网页登录百度网盘后可参考这篇文章获取
[https://www.cnbanwagong.com/cookie.html](https://www.cnbanwagong.com/cookie.html)
主要获取cookie:后面的参数

**Comment by Xiegiter** [comment]
您好，想问一下，本地如何打开文件夹批量下载？

**Comment by huankong233** [comment]
> 兄台，我说的是那个添加管理员的cookie，是从哪获取的，不是获取cookie

是获取列表的cookie吗？

还是这个session

https://github.com/codehub666/94list/blob/3f54674e4c8bbf33525b085d7917a50fb6279d92/function.php#L64-L108

**Comment by codehub666** [comment]
获取列表的cookie也是百度账号cookie，和解析账号的cookie一样的

**Comment by huankong233** [comment]
获取列表的cookie是不需要登陆的，如果登陆账号会被临时进入解析黑名单

**Comment by codehub666** [comment]
> 获取列表的cookie是不需要登陆的，如果登陆账号会被临时进入解析黑名单

啊！现在不需要了嘛，之前没 CK 不给获取列表

**Comment by harrissherlock** [comment]
这个无需登录是指要把网页里登录的账号退出登录吗？临时进入解析黑名单会持续多久？

**Comment by harrissherlock** [comment]
> > 获取列表的cookie是不需要登陆的，如果登陆账号会被临时进入解析黑名单
> 
> 啊！现在不需要了嘛，之前没 CK 不给获取列表
这个无需登录是指要把网页里登录的账号退出登录吗？临时进入解析黑名单会持续多久？CK是什么

**Comment by harrissherlock** [comment]
现在是卡在第一个界面的获取列表的cookie，一旦输入了获取列表账号的cookie，就会导致在下载的时候直接把仓库里的账号封禁了，有大佬知道是什么原因吗？这个获取列表的cookie应该填写什么？

**Comment by huankong233** [comment]
> > 获取列表的cookie是不需要登陆的，如果登陆账号会被临时进入解析黑名单
> 
> 啊！现在不需要了嘛，之前没 CK 不给获取列表

ck是需要的，只是ck不需要对应一个账户

**Comment by huankong233** [comment]
> 现在是卡在第一个界面的获取列表的cookie，一旦输入了获取列表账号的cookie，就会导致在下载的时候直接把仓库里的账号封禁了，有大佬知道是什么原因吗？这个获取列表的cookie应该填写什么？

翻一下issues我回复过

**Comment by harrissherlock** [comment]
> > 现在是卡在第一个界面的获取列表的cookie，一旦输入了获取列表账号的cookie，就会导致在下载的时候直接把仓库里的账号封禁了，有大佬知道是什么原因吗？这个获取列表的cookie应该填写什么？
> 
> 翻一下issues我回复过

没大看明白获取列表的cookie不要登录的意思，方面的话能不能麻烦大佬远程指导一下，还有一点点其它的小问题，谢谢大佬了！QQ2985694296

**Comment by huankong233** [comment]
> > > 现在是卡在第一个界面的获取列表的cookie，一旦输入了获取列表账号的cookie，就会导致在下载的时候直接把仓库里的账号封禁了，有大佬知道是什么原因吗？这个获取列表的cookie应该填写什么？
> > 
> > 
> > 翻一下issues我回复过
> 
> 没大看明白获取列表的cookie不要登录的意思，方面的话能不能麻烦大佬远程指导一下，还有一点点其它的小问题，谢谢大佬了！QQ2985694296

浏览器打开无痕模式，然后进入pan.baidu.com然后复制现在的cookie即可，不需要其他任何操作

**Comment by harrissherlock** [comment]
是这个样子吗？

![_11{PAQT48(}3 JD871(0OK](https://github.com/codehub666/94list/assets/148022426/fd6b18f8-7dd7-4b97-83d0-6229b946f531)

**Comment by harrissherlock** [comment]
提示，
![7}PSIMQV38V9RAALDCV_(UD](https://github.com/codehub666/94list/assets/148022426/c6f41065-8cfb-44da-b2bb-6a1dc283161a)

然后账号就寄了

**Comment by huankong233** [comment]
> 提示， ![7}PSIMQV38V9RAALDCV_(UD](https://user-images.githubusercontent.com/148022426/280182110-c6f41065-8cfb-44da-b2bb-6a1dc283161a.png)
> 
> 然后账号就寄了

那就是账户被封了呀，不是获取列表的问题

**Comment by harrissherlock** [comment]
我是用新的账号去尝试的。获取列表的cookie是我上面发的那个图片里的那种样子对吗？

**Comment by huankong233** [comment]
> 我是用新的账号去尝试的。获取列表的cookie是我上面发的那个图片里的那种样子对吗？

对，那有可能ip黑了

**Comment by harrissherlock** [comment]
我换了实验室的网，也是这挂了vpn，也试着新创了一个新的百度网号，但是仍然提示错误代码9019，无奈了

**Comment by huankong233** [comment]
> 我换了实验室的网，也是这挂了vpn，也试着新创了一个新的百度网号，但是仍然提示错误代码9019，无奈了

你开全局了吗，可能没有代理到 pan.baidu.com 这个域名

**Comment by harrissherlock** [comment]
是全局没错
![image](https://github.com/codehub666/94list/assets/148022426/ce72662b-46cc-4d11-8fb2-566050f16892)

**Comment by huankong233** [comment]
> 是全局没错 ![image](https://user-images.githubusercontent.com/148022426/280232656-ce72662b-46cc-4d11-8fb2-566050f16892.png)

那还真就不清楚了🤔，你手动去分享链接那里拉起百度网盘，可以自动弹出下载框吗

**Comment by huankong233** [comment]
> > 是全局没错 ![image](https://user-images.githubusercontent.com/148022426/280232656-ce72662b-46cc-4d11-8fb2-566050f16892.png)
> 
> 那还真就不清楚了🤔，你手动去分享链接那里拉起百度网盘，可以自动弹出下载框吗

接口是这里抓到的

**Comment by harrissherlock** [comment]
这个手动去分享链接拉起百度网盘是指什么
![7CM3{ADE0E0(F27HW%B7P~L](https://github.com/codehub666/94list/assets/148022426/e77e5e16-4fe2-4c65-a435-16fcbdbba4d7)
是指这个吗

**Comment by harrissherlock** [comment]
![1814764Z5WHEZS5C0(I1LKN](https://github.com/codehub666/94list/assets/148022426/19aeb4fb-23fc-4778-a234-f8eb38c830fd)

**Comment by harrissherlock** [comment]
![1814764Z5WHEZS5C0(I1LKN](https://github.com/codehub666/94list/assets/148022426/a45e7157-f849-4216-87b4-e053a7b85204)
是能正常弹出下载框去下载的

**Comment by huankong233** [comment]
> ![1814764Z5WHEZS5C0(I1LKN](https://user-images.githubusercontent.com/148022426/280252722-a45e7157-f849-4216-87b4-e053a7b85204.png) 是能正常弹出下载框去下载的

可以拉起百度网盘，然后在百度网盘里面弹下载框吗

**Comment by huankong233** [comment]
> ![1814764Z5WHEZS5C0(I1LKN](https://user-images.githubusercontent.com/148022426/280252722-a45e7157-f849-4216-87b4-e053a7b85204.png) 是能正常弹出下载框去下载的

可以拉起百度网盘，然后在百度网盘里面弹下载框吗
