### ISSUE TITLE
报错了诶【已解决】

### ISSUE THREAD

**Issue by yimu56** [codehub666/94list#2]
![Snipaste_2023-08-22_20-27-07](https://github.com/codehub666/94list/assets/90325203/f38755fb-76b8-4b6a-a0a9-b6da24a3af90)
![Snipaste_2023-08-22_20-26-28](https://github.com/codehub666/94list/assets/90325203/1e6034bd-d044-4593-87bc-66b26ff66aa8)
![Snipaste_2023-08-22_20-27-19](https://github.com/codehub666/94list/assets/90325203/5b695128-3c60-47d7-880d-0af9b0615487)

**Comment by codehub666** [comment]
理应是不该存在空白回调。出空白回调估计是出错误。
对了！！PHP还需要mysqli扩展，估计你PHP缺少这个扩展造成无法对接。
宝塔部署的环境都是默认有引用这个扩展的，你这个环境部署面板应该就没有。

**Comment by yimu56** [comment]
是这个吗，一直都有诶
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月22日 22:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [codehub666/94list] 报错了诶 (Issue #2)


理应是不该存在空白回调。出空白回调估计是出错误。
对了！！PHP还需要mysqli扩展，估计你PHP缺少这个扩展造成无法对接。
宝塔部署的环境都是默认有引用这个扩展的，你这个环境部署面板应该就没有。

―

**Comment by codehub666** [comment]
[https://github.com/codehub666/94list/issues/15](url)
PHP写法对一些环境不友好，可更新一下代码进行解决。
