### ISSUE TITLE
api.js 页面404【已解决】

### ISSUE THREAD

**Issue by chenhuihuangzxc** [codehub666/94list#21]
环境为：
PHP 8.0.30
nginx/1.20.1
centos7.6
nginx转发到php-fpm

一直出现下图api.js页面报404，后面将admin/index.js的相关/api.php/修改为/api.php页面上才能正常获取到代理账号信息，不知道是不是我这边nginx代理导致的
<img width="1280" alt="_20230910212931" src="https://github.com/codehub666/94list/assets/38641346/99b761fb-9f27-4271-87e2-3ae3fc46cf66">
<img width="1260" alt="20230910214117" src="https://github.com/codehub666/94list/assets/38641346/8f5d3e53-45a7-42ed-87cd-0ca7d8fd9a4a">

**Comment by codehub666** [comment]
有的环境比较严格就会这样，这个index.js文件请求api.php文件少改了一个。我已追加修改。

**Comment by qaz11ac** [comment]
<img width="505" alt="屏幕截图 2023-09-11 045225" src="https://github.com/codehub666/94list/assets/144626630/fed81394-6742-418a-a4af-266b38fb2b48">
我的是这样的 然后在后台更换会员账号一直报cookie错误

**Comment by codehub666** [comment]
> <img alt="屏幕截图 2023-09-11 045225" width="505" src="https://user-images.githubusercontent.com/144626630/266867829-fed81394-6742-418a-a4af-266b38fb2b48.png"> 我的是这样的 然后在后台更换会员账号一直报cookie错误

建议清除缓存在重新登录获取cookie，已在问主问帖里面进行远程解决
