### ISSUE TITLE
作者你好，管理后台更换账号显示cookie有误，我已截图你得空看一下是什么原因呢 谢谢【已解决】

### ISSUE THREAD

**Issue by qaz11ac** [codehub666/94list#23]
<img width="633" alt="屏幕截图 2023-09-11 041321" src="https://github.com/codehub666/94list/assets/144626630/02d1a4ed-3a2a-469a-b47b-35987d7a5c74">

**Comment by qaz11ac** [comment]
![Uploading 屏幕截图 2023-09-11 045225.png…]()

**Comment by qaz11ac** [comment]
<img width="505" alt="屏幕截图 2023-09-11 045225" src="https://github.com/codehub666/94list/assets/144626630/38f973a2-45d7-4213-a49e-60fb58d01dbd">

**Comment by codehub666** [comment]
看看会不会cookie前面有多出个空格，或者你+qq2797572563给你看一下

**Comment by codehub666** [comment]
远程解决了。建议先清除一下缓存cookie，然后重新登录在获取cookie。

**Comment by huankong233** [comment]
这个cookie的问题其实是原版上传cookie使用了表单上传，在遇到cookie中存在&时会出现把参数分割导致后续有的参数获取失败导致报错的问题，使用json传递即可解决

**Comment by codehub666** [comment]
> 这个cookie的问题其实是原版上传cookie使用了表单上传，在遇到cookie中存在&时会出现把参数分割导致后续有的参数获取失败导致报错的问题，使用json传递即可解决

确实是符号引起的冲突 👍

**Comment by Markli66** [comment]
请教一下，按照上面所说的方式应该怎么修改成为JSON格式才能正常传递，在index.js中设置后后台传递的参数依然还是会有错误的。

**Comment by huankong233** [comment]
> 请教一下，按照上面所说的方式应该怎么修改成为JSON格式才能正常传递，在index.js中设置后后台传递的参数依然还是会有错误的。

https://github.com/codehub666/94list/blob/3f54674e4c8bbf33525b085d7917a50fb6279d92/admin/index.js#L48-L91

两个方法里的axios.post的第二个参数应该用json格式

**Comment by yuantuo666** [comment]
> 这个cookie的问题其实是原版上传cookie使用了表单上传，在遇到cookie中存在&时会出现把参数分割导致后续有的参数获取失败导致报错的问题，使用json传递即可解决

正经的写法应该是把要上传的内容 UrlEncode 下。

正常情况下，你写一个 form 表单填写内容后提交它，PHP 接收到的是正确的内容，抓包可以发现是浏览器自动 encode 了，而这里的代码是手动拼接的字符串，没有进行这个操作所以会出问题。

附上测试代码
```
<?php
var_dump($_POST);
?>

<form method="post">
    <input type="text" name="name" placeholder="Name">
    <button>Submit</button>
</form>

```
<img width="785" alt="image" src="https://github.com/codehub666/94list/assets/44130602/c99dfc01-f83e-4598-80f0-a95e220e8471">
