### ISSUE TITLE
能不能借个一个号用一下，我做测试用【已解决】

### ISSUE THREAD

**Issue by huankong233** [codehub666/94list#24]
我用laravel重写了这个项目，现在后台管理部分写完了，现在就差前台解析链接了，就想借一个号
[https://github.com/huankong233/94list-laravel](https://github.com/huankong233/94list-laravel)

**Comment by codehub666** [comment]
可以留个邮箱嘛，我在你的主页和博客均找不到你的联系方式。COOKIE不能公开，不然很快会失效或者被盗用。

**Comment by huankong233** [comment]
> 可以留个邮箱嘛，我在你的主页和博客均找不到你的联系方式。COOKIE不能公开，不然很快会失效或者被盗用。

你的邮箱是多少，我给你发个信息

**Comment by codehub666** [comment]
> > 可以留个邮箱嘛，我在你的主页和博客均找不到你的联系方式。COOKIE不能公开，不然很快会失效或者被盗用。
> 
> 你的邮箱是多少，我给你发个信息

[a94author@outlook.com](mailto:a94author@outlook.com)

**Comment by codehub666** [comment]
2797572563qq.com

**Comment by huankong233** [comment]
> 2797572563qq.com

发了

**Comment by huankong233** [comment]
谢谢

**Comment by codehub666** [comment]
收到，已将cookie发送给你

**Comment by huankong233** [comment]
![image](https://github.com/codehub666/94list/assets/49610758/606495bb-31c7-48ed-a325-701298f96276)
$root后的=是必要的吗
![image](https://github.com/codehub666/94list/assets/49610758/508bf3ec-cc5c-48ad-ae7f-aea3cb748487)
就是这个最后的=

**Comment by huankong233** [comment]
~~~ php
$requestData = [ // app\Http\Controllers\UserController.php:79
  "shorturl" => "1LRhZlkazAzC2x-u2euRH7g",
  "dir" => null,
  "root" => 0,
  "pwd" => "vc3b",
  "page" => 1,
  "num" => 10,
  "order" => "time"
];
~~~

获取到的响应是

~~~php
$response = [ // app\Http\Controllers\UserController.php:79
  "errno" => -130,
  "request_id" => 脱敏,
  "errtype" => "mis_2",
  "server_time" => 1694501592,
  "data" => [
    "title" => "",
    "expiredType" => 30,
    "link_ctime" => 1694501247,
    "fileNums" => 0,
    "has_more" => false,
    "list" => [],
    "user" => [
      "avatar" => "脱敏"
    ]
    "uname" => "脱敏",
    "uk" => 脱敏,
    "shareid" => 脱敏,
    "wx_name" => "脱敏",
    "wx_headurl" => "脱敏",
    "hitrisk" => 0,
    "appeal_status" => 0,
    "sharetype" => 0,
    "view_visited" => 0,
    "view_limit" => 0,
    "expired_type" => 30,
    "seckey" => "脱敏",
  ]
  "cfrom_id" => 0,
  "is_zombie" => 0,
  "vip_point" => 0,
  "vip_level" => 1,
  "svip10_id" => "",
  "vip_type" => 0
]
~~~

有一部分的数据获取成功了

**Comment by huankong233** [comment]
> ```
> $requestData = [ // app\Http\Controllers\UserController.php:79
>   "shorturl" => "1LRhZlkazAzC2x-u2euRH7g",
>   "dir" => null,
>   "root" => 0,
>   "pwd" => "vc3b",
>   "page" => 1,
>   "num" => 10,
>   "order" => "time"
> ];
> ```
> 
> 获取到的响应是
> 
> ```
> $response = [ // app\Http\Controllers\UserController.php:79
>   "errno" => -130,
>   "request_id" => 脱敏,
>   "errtype" => "mis_2",
>   "server_time" => 1694501592,
>   "data" => [
>     "title" => "",
>     "expiredType" => 30,
>     "link_ctime" => 1694501247,
>     "fileNums" => 0,
>     "has_more" => false,
>     "list" => [],
>     "user" => [
>       "avatar" => "脱敏"
>     ]
>     "uname" => "脱敏",
>     "uk" => 脱敏,
>     "shareid" => 脱敏,
>     "wx_name" => "脱敏",
>     "wx_headurl" => "脱敏",
>     "hitrisk" => 0,
>     "appeal_status" => 0,
>     "sharetype" => 0,
>     "view_visited" => 0,
>     "view_limit" => 0,
>     "expired_type" => 30,
>     "seckey" => "脱敏",
>   ]
>   "cfrom_id" => 0,
>   "is_zombie" => 0,
>   "vip_point" => 0,
>   "vip_level" => 1,
>   "svip10_id" => "",
>   "vip_type" => 0
> ]
> ```
> 
> 有一部分的数据获取成功了

带上cookie了

**Comment by huankong233** [comment]
发现问题了 https://github.com/codehub666/94list/blob/cc49bacc98a5be09ca87cc4092a9e597e1198aa0/function.php#L472

应该是
~~~ php
$dir !== '' ? 1 : 0
~~~
