### ISSUE TITLE
作者你好,搭建都完成了 但是在调用Motrix下载 调用不了

### ISSUE THREAD

**Issue by zz6853** [codehub666/94list#25]
调用显示发送失败
![看图王截图20230914025911](https://github.com/codehub666/94list/assets/58268737/b2e1c45f-4a45-4a0b-af29-c7c50d161b5d)

**Comment by codehub666** [comment]
Motrix下载器的 基础设置->进阶设置->恢复初始 点击重启一下下载器。
问题好像不在于JS发送，而是Motrix下载器本身存在未知问题？？

**Comment by huankong233** [comment]
这个可能是chrome的安全机制，原版在调用Motrix时未提供secret可能会出现问题

**Comment by huankong233** [comment]
> 这个可能是chrome的安全机制，原版在调用Motrix时未提供secret可能会出现问题

https://github.com/codehub666/94list/blob/3f54674e4c8bbf33525b085d7917a50fb6279d92/assets/js/index.js#L56-L82

**Comment by huankong233** [comment]
> 这个可能是chrome的安全机制
> 
> 也可能是在调用Motrix时未提供secret

https://github.com/codehub666/94list/blob/3f54674e4c8bbf33525b085d7917a50fb6279d92/assets/js/index.js#L56-L82

饼先画在这里了

https://github.com/huankong233/94list-laravel/blob/f49231badf0a307648ee8f5cf0153a449f891c0d/resources/views/pages/user.blade.php#L396-L436

**Comment by zz6853** [comment]
> Motrix下载器的 基础设置->进阶设置->恢复初始 点击重启一下下载器。 问题好像不在于JS发送，而是Motrix下载器本身存在未知问题？？

但是用你搭建的还是可以调起下载的 用其他源码也是可以的
https://github.com/yuantuo666/baiduwp-php

**Comment by zz6853** [comment]
> Motrix下载器的 基础设置->进阶设置->恢复初始 点击重启一下下载器。 问题好像不在于JS发送，而是Motrix下载器本身存在未知问题？？

恢复初始 点击重启一下下载器 还是一样不行

**Comment by huankong233** [comment]
> > Motrix下载器的 基础设置->进阶设置->恢复初始 点击重启一下下载器。 问题好像不在于JS发送，而是Motrix下载器本身存在未知问题？？
> 
> 恢复初始 点击重启一下下载器 还是一样不行

打开开发者工具，切换到console页面截图看一下

**Comment by huankong233** [comment]
![9655ac255bb9624c2aab9e888b4069f7](https://github.com/codehub666/94list/assets/49610758/6b371b61-89f5-4cd0-a934-4829d8dca348)

好消息是我写的Motrix和Aria2已经完美支持了（应该）

**Comment by zz6853** [comment]
> > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > 
> > 
> > 恢复启动点击重启一下下载器还是一样失败
> 
> 打开开发者工具，切换到控制台页面截图看一下
是这个吗
![看图王截图20230914151848](https://github.com/codehub666/94list/assets/58268737/3ea53f91-d130-4daa-8c19-5d5f08e71ba6)

**Comment by huankong233** [comment]
> > > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > > 
> > > 
> > > 恢复启动点击重启一下下载器还是一样失败
> > 
> > 
> > 打开开发者工具，切换到控制台页面截图看一下
> > 是这个吗
> > ![看图王截图20230914151848](https://user-images.githubusercontent.com/58268737/267890733-3ea53f91-d130-4daa-8c19-5d5f08e71ba6.png)

是这个，你点网络那一栏再看一下

**Comment by huankong233** [comment]
> > > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > > 
> > > 
> > > 恢复启动点击重启一下下载器还是一样失败
> > 
> > 
> > 打开开发者工具，切换到控制台页面截图看一下
> > 是这个吗
> > ![看图王截图20230914151848](https://user-images.githubusercontent.com/58268737/267890733-3ea53f91-d130-4daa-8c19-5d5f08e71ba6.png)

有一个jsonrpc结尾的

**Comment by zz6853** [comment]
> > > > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > > > 
> > > > 
> > > > 恢复启动点击重启一下下载器还是一样失败
> > > 
> > > 
> > > 打开开发者工具，切换到控制台页面截图看一下
> > > 是这个吗
> > > ![看图王截图20230914151848](https://user-images.githubusercontent.com/58268737/267890733-3ea53f91-d130-4daa-8c19-5d5f08e71ba6.png)
> 
> 有一个 jsonrpc 结尾的

![Uploading 看图王截图20230914152804.png…]()

**Comment by huankong233** [comment]
> > > > > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > > > > 
> > > > > 
> > > > > 恢复启动点击重启一下下载器还是一样失败
> > > > 
> > > > 
> > > > 打开开发者工具，切换到控制台页面截图看一下
> > > > 是这个吗
> > > > ![看图王截图20230914151848](https://user-images.githubusercontent.com/58268737/267890733-3ea53f91-d130-4daa-8c19-5d5f08e71ba6.png)
> > 
> > 
> > 有一个 jsonrpc 结尾的
> 
> ![看图王截图20230914153014](https://user-images.githubusercontent.com/58268737/267893419-c9353ca5-06fd-4768-94fc-27f9f3e15d20.png)

记得打码服务器ip，这个是CORS政策的问题

**Comment by huankong233** [comment]
> > > > > > Motrix下载器的基础设置->进阶设置->重启点击重启一下下载器。问题好像不支持JS连接，但是Motrix下载器本身存在未知问题？
> > > > > 
> > > > > 
> > > > > 恢复启动点击重启一下下载器还是一样失败
> > > > 
> > > > 
> > > > 打开开发者工具，切换到控制台页面截图看一下
> > > > 是这个吗
> > > > ![看图王截图20230914151848](https://user-images.githubusercontent.com/58268737/267890733-3ea53f91-d130-4daa-8c19-5d5f08e71ba6.png)
> > 
> > 
> > 有一个 jsonrpc 结尾的
> 
> ![看图王截图20230914153014](https://user-images.githubusercontent.com/58268737/267893419-c9353ca5-06fd-4768-94fc-27f9f3e15d20.png)

![image](https://github.com/codehub666/94list/assets/49610758/8fa94a7f-ec0b-4ca3-bffb-6635a73ad4f7)

检查是否打开了这个选项

![image](https://github.com/codehub666/94list/assets/49610758/97b3265c-879c-4942-8f24-f1b995201170)

**Comment by zz6853** [comment]
![看图王截图20230914154018](https://github.com/codehub666/94list/assets/58268737/cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff)
这是都打开了吧

**Comment by huankong233** [comment]
> ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png) 这是都打开了吧

🤷‍♂️，应该是的

**Comment by huankong233** [comment]
> ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png) 这是都打开了吧

![image](https://github.com/codehub666/94list/assets/49610758/04f6d172-1493-45eb-8400-5b30fd0363b1)

这就不是很清楚为什么了，我这边是可以用的

**Comment by huankong233** [comment]
> ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png) 这是都打开了吧

尝试此[方法](https://blog.csdn.net/Flywithdawn/article/details/128253604)

可能是打开了那个增强安全模式

**Comment by zz6853** [comment]
> > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png) 这是都打开了吧
> 
> ![image](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> 
> 这就不是很清楚为什么了，我这边是可以用的

![看图王截图20230914154521](https://github.com/codehub666/94list/assets/58268737/ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43)
但是我用另一个就可以调用

**Comment by huankong233** [comment]
> > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png) 这是都打开了吧
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > 这就不是很清楚为什么了，我这边是可以用的
> 
> ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png) 但是我用另一个就可以调用

可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了

**Comment by zz6853** [comment]
> > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > 这不是很清楚为什么了，我的香料是可以用的
> > 
> > 
> > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> 
> 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了

好哒 谢谢啦

**Comment by huankong233** [comment]
> > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > 
> > > > 
> > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > 这不是很清楚为什么了，我的香料是可以用的
> > > 
> > > 
> > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > 
> > 
> > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> 
> 好哒 谢谢啦

我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求

**Comment by codehub666** [comment]
> > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > 
> > > > > 
> > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > 
> > > > 
> > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > 
> > > 
> > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > 
> > 
> > 好哒 谢谢啦
> 
> 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求

真相了，突然想起来之前演示站没SSL是会提示安全的问题的

**Comment by huankong233** [comment]
> > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > 
> > > > > > 
> > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > 
> > > > > 
> > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > 
> > > > 
> > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > 
> > > 
> > > 好哒 谢谢啦
> > 
> > 
> > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> 
> 真相了，突然想起来之前演示站没SSL是会提示安全的问题的

我回头加一个提醒

**Comment by huankong233** [comment]
> > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > 
> > > > > > > 
> > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > 
> > > > > > 
> > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > 
> > > > > 
> > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > 
> > > > 
> > > > 好哒 谢谢啦
> > > 
> > > 
> > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > 
> > 
> > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> 
> 我回头加一个提醒

![image](https://github.com/codehub666/94list/assets/49610758/0bf5ffc8-7597-4406-96da-fb69ae98bc0a)

😎

**Comment by codehub666** [comment]
> > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > 
> > > > > > > 
> > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > 
> > > > > > 
> > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > 
> > > > > 
> > > > > 好哒 谢谢啦
> > > > 
> > > > 
> > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > 
> > > 
> > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > 
> > 
> > 我回头加一个提醒
> 
> ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> 
> 😎

矮油，不错哟

**Comment by huankong233** [comment]
> > > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > > 
> > > > > > > 
> > > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > > 
> > > > > > 
> > > > > > 好哒 谢谢啦
> > > > > 
> > > > > 
> > > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > > 
> > > > 
> > > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > > 
> > > 
> > > 我回头加一个提醒
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> > 😎
> 
> 矮油，不错哟

你可以去部署一个试试看，现在功能已经做的差不多了，可以帮我试试看有没有什么bug

**Comment by huankong233** [comment]
> > > > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > > > 
> > > > > > > 
> > > > > > > 好哒 谢谢啦
> > > > > > 
> > > > > > 
> > > > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > > > 
> > > > > 
> > > > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > > > 
> > > > 
> > > > 我回头加一个提醒
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> > > 😎
> > 
> > 
> > 矮油，不错哟
> 
> 你可以去部署一个试试看，现在功能已经做的差不多了，可以帮我试试看有没有什么bug

这个项目里的bug，我发现了不少，cookie上传的时候还会被分割开，数据应该用post传输的，都是用的get

**Comment by codehub666** [comment]
> > > > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > > > 
> > > > > > > 
> > > > > > > 好哒 谢谢啦
> > > > > > 
> > > > > > 
> > > > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > > > 
> > > > > 
> > > > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > > > 
> > > > 
> > > > 我回头加一个提醒
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> > > 😎
> > 
> > 
> > 矮油，不错哟
> 
> 你可以去部署一个试试看，现在功能已经做的差不多了，可以帮我试试看有没有什么bug

等你完工了我在全方位试一下吧，现在在忙其他的  ( : 悲

**Comment by huankong233** [comment]
> > > > > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 好哒 谢谢啦
> > > > > > > 
> > > > > > > 
> > > > > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > > > > 
> > > > > > 
> > > > > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > > > > 
> > > > > 
> > > > > 我回头加一个提醒
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> > > > 😎
> > > 
> > > 
> > > 矮油，不错哟
> > 
> > 
> > 你可以去部署一个试试看，现在功能已经做的差不多了，可以帮我试试看有没有什么bug
> 
> 等你完工了我在全方位试一下吧，现在在忙其他的 ( : 悲

好🤷‍♂️，就差一个分页应该就完工了，你看看还缺什么功能

### 前台

- [x] 前台文件列表解析
- [x] 前台文件列表进入退出
- [x] 前台下载链接解析
- [x] 批量解析/下载
- [ ] 列表分页

### 后台

- [x] 后台配置修改
- [x] 后台账户添加删除禁用
- [x] 后台账户可用性完成
- [x] 管理员账号密码修改
- [x] 指定账号解析测试

**Comment by codehub666** [comment]
> > > > > > > > > > > > > ![看图王截图20230914154018](https://user-images.githubusercontent.com/58268737/267897443-cd0ddecb-80f9-490c-bf61-b7d9b7e4f3ff.png)这都打开了吧
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > ![图像](https://user-images.githubusercontent.com/49610758/267898167-04f6d172-1493-45eb-8400-5b30fd0363b1.png)
> > > > > > > > > > > > 这不是很清楚为什么了，我的香料是可以用的
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > ![看图王截图20230914154521](https://user-images.githubusercontent.com/58268737/267898962-ec6b6462-3d45-4dbc-9d7f-8e0e84f6fc43.png)但是我用另一个就可以调用
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 可能因为请求方式不同，你可以试试看我写的那个，现在基础功能（解析，批量下载等）都已经完成了
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 好哒 谢谢啦
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我知道问题了，别人部署了之后访问应该是https打头吧，那是安全连接，可能chrome判断你自己搭建的没有启用https/ssl，所以禁止了往localhost发送请求
> > > > > > > 
> > > > > > > 
> > > > > > > 真相了，突然想起来之前演示站没SSL是会提示安全的问题的
> > > > > > 
> > > > > > 
> > > > > > 我回头加一个提醒
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/49610758/267947332-0bf5ffc8-7597-4406-96da-fb69ae98bc0a.png)
> > > > > 😎
> > > > 
> > > > 
> > > > 矮油，不错哟
> > > 
> > > 
> > > 你可以去部署一个试试看，现在功能已经做的差不多了，可以帮我试试看有没有什么bug
> > 
> > 
> > 等你完工了我在全方位试一下吧，现在在忙其他的 ( : 悲
> 
> 好🤷‍♂️，就差一个分页应该就完工了，你看看还缺什么功能
> 
> ### 前台
> * [x]  前台文件列表解析
> * [x]  前台文件列表进入退出
> * [x]  前台下载链接解析
> * [x]  批量解析/下载
> * [ ]  列表分页
> 
> ### 后台
> * [x]  后台配置修改
> * [x]  后台账户添加删除禁用
> * [x]  后台账户可用性完成
> * [x]  管理员账号密码修改
> * [x]  指定账号解析测试

基本是超越原版了，你可以加个 链接GET 分享参数和密码的，这样方便用户去分享资源。
