### ISSUE TITLE
【兼容性反馈】发送到Aria2功能被谷歌浏览器拦截

### ISSUE THREAD

**Issue by 1Q23LYC45** [codehub666/94list#27]
如题，火狐和IE没问题，谷歌系列浏览器在解析链接成功后
系统终端输入aria2c --enable-rpc --rpc-listen-all 启动RPC远程下载服务后
点击“发送到Aria2”，提示发送失败。抓包，没有到aria2rpc服务器的连接。F12控制台输出错误如下：
Access to XMLHttpRequest at 'http://127.0.0.1:6800' from origin 'http://192.168.10.2:8080' has been blocked by CORS policy
目前已找到不完美解决方法，需要用户手动操作：
Chrome 92及以下版本：安装插件Cross Domain - CORS
Chrome 93-107版本：安装插件Cross Domain - CORS，然后还要打开链接
chrome://flags/#block-insecure-private-network-requests
禁用block-insecure-private-network-requests功能
Chrome 108及以上版本：暂时无解，谷歌删除了链接
但是我不想每次使用都装个插件，然后一顿改设置才能使用。我更希望能一键发送链接，不用任何设置。
希望解决，谢谢！
我的服务器：lighttpd/1.4.71，php版本8.2.8。没有伪静态。

**Comment by huankong233** [comment]
> 如题，火狐和IE没问题，谷歌系列浏览器在解析链接成功后 系统终端输入aria2c --enable-rpc --rpc-listen-all 启动RPC远程下载服务后 点击“发送到Aria2”，提示发送失败。抓包，没有到aria2rpc服务器的连接。F12控制台输出错误如下： Access to XMLHttpRequest at 'http://127.0.0.1:6800' from origin 'http://192.168.10.2:8080' has been blocked by CORS policy 目前已找到不完美解决方法，需要用户手动操作： Chrome 92及以下版本：安装插件Cross Domain - CORS Chrome 93-107版本：安装插件Cross Domain - CORS，然后还要打开链接 chrome://flags/#block-insecure-private-network-requests 禁用block-insecure-private-network-requests功能 Chrome 108及以上版本：暂时无解，谷歌删除了链接 但是我不想每次使用都装个插件，然后一顿改设置才能使用。我更希望能一键发送链接，不用任何设置。 希望解决，谢谢！ 我的服务器：lighttpd/1.4.71，php版本8.2.8。没有伪静态。

只需要在本地服务器启用SSL即可，也就是在 `192.168.10.2` 这台服务器上加上SSL

**Comment by huankong233** [comment]
> 如题，火狐和IE没问题，谷歌系列浏览器在解析链接成功后 系统终端输入aria2c --enable-rpc --rpc-listen-all 启动RPC远程下载服务后 点击“发送到Aria2”，提示发送失败。抓包，没有到aria2rpc服务器的连接。F12控制台输出错误如下： Access to XMLHttpRequest at 'http://127.0.0.1:6800' from origin 'http://192.168.10.2:8080' has been blocked by CORS policy 目前已找到不完美解决方法，需要用户手动操作： Chrome 92及以下版本：安装插件Cross Domain - CORS Chrome 93-107版本：安装插件Cross Domain - CORS，然后还要打开链接 chrome://flags/#block-insecure-private-network-requests 禁用block-insecure-private-network-requests功能 Chrome 108及以上版本：暂时无解，谷歌删除了链接 但是我不想每次使用都装个插件，然后一顿改设置才能使用。我更希望能一键发送链接，不用任何设置。 希望解决，谢谢！ 我的服务器：lighttpd/1.4.71，php版本8.2.8。没有伪静态。

强制走不安全的SSL应该也不行的，你是需要内网穿透后走这个地址吗

**Comment by huankong233** [comment]
> 如题，火狐和IE没问题，谷歌系列浏览器在解析链接成功后 系统终端输入aria2c --enable-rpc --rpc-listen-all 启动RPC远程下载服务后 点击“发送到Aria2”，提示发送失败。抓包，没有到aria2rpc服务器的连接。F12控制台输出错误如下： Access to XMLHttpRequest at 'http://127.0.0.1:6800' from origin 'http://192.168.10.2:8080' has been blocked by CORS policy 目前已找到不完美解决方法，需要用户手动操作： Chrome 92及以下版本：安装插件Cross Domain - CORS Chrome 93-107版本：安装插件Cross Domain - CORS，然后还要打开链接 chrome://flags/#block-insecure-private-network-requests 禁用block-insecure-private-network-requests功能 Chrome 108及以上版本：暂时无解，谷歌删除了链接 但是我不想每次使用都装个插件，然后一顿改设置才能使用。我更希望能一键发送链接，不用任何设置。 希望解决，谢谢！ 我的服务器：lighttpd/1.4.71，php版本8.2.8。没有伪静态。

有一个解决办法，那就是 `kinh` 之前的方法，生成命令，然后你自己去执行就可以了，不用网络请求来让aria2添加下载任务

**Comment by huankong233** [comment]
> 如题，火狐和IE没问题，谷歌系列浏览器在解析链接成功后 系统终端输入aria2c --enable-rpc --rpc-listen-all 启动RPC远程下载服务后 点击“发送到Aria2”，提示发送失败。抓包，没有到aria2rpc服务器的连接。F12控制台输出错误如下： Access to XMLHttpRequest at 'http://127.0.0.1:6800' from origin 'http://192.168.10.2:8080' has been blocked by CORS policy 目前已找到不完美解决方法，需要用户手动操作： Chrome 92及以下版本：安装插件Cross Domain - CORS Chrome 93-107版本：安装插件Cross Domain - CORS，然后还要打开链接 chrome://flags/#block-insecure-private-network-requests 禁用block-insecure-private-network-requests功能 Chrome 108及以上版本：暂时无解，谷歌删除了链接 但是我不想每次使用都装个插件，然后一顿改设置才能使用。我更希望能一键发送链接，不用任何设置。 希望解决，谢谢！ 我的服务器：lighttpd/1.4.71，php版本8.2.8。没有伪静态。

sqlite的话我回头应该会支持一下，晚点看一下，laravel的话原生是就直接支持sqlite，只需要切换一下驱动器即可

**Comment by 1Q23LYC45** [comment]
谢谢大佬 我确实是内网穿透的 本地测试用的192.168.10.2。

**Comment by huankong233** [comment]
https://github.com/codehub666/94list/issues/25
