### ISSUE TITLE
下了源代码之后要怎么运行【已解决】

### ISSUE THREAD

**Issue by wilson2009715** [codehub666/94list#3]
下了源代码之后要怎么运行啊
![屏幕截图 2023-08-23 003808](https://github.com/codehub666/94list/assets/142913122/e77287aa-e289-4670-810b-ec2866ffde97)

**Comment by wilson2009715** [comment]
第一次用这个，见谅

**Comment by 1925888818** [comment]
需要服务器的喔 最简单的方法下个宝塔面板然后一步一步走就好啦

**Comment by codehub666** [comment]
如楼上所言，需要有服务器进行部署
