### ISSUE TITLE
发送到Motrix下载报24错误是什么原因呢 希望得到作者的回复 谢谢

### ISSUE THREAD

**Issue by qaz11ac** [codehub666/94list#30]
发送到Motrix下载报24错误是什么原因呢 希望得到作者的回复 谢谢

**Comment by huankong233** [comment]
https://github.com/codehub666/94list/issues/25

请先查看本issues

**Comment by huankong233** [comment]
还是说发送成功了，但是Motrix内报24错误，那可能是下载未携带UA，造成返回了403错误

**Comment by qaz11ac** [comment]
> 还是说发送成功了，但是Motrix内报24错误，那可能是下载未携带UA，造成返回了403错误

发送成功了 在Motrix里报24错误有时报22错误 都是在Motrix里

**Comment by qaz11ac** [comment]
> 还是说发送成功了，但是Motrix内报24错误，那可能是下载未携带UA，造成返回了403错误

大佬 可以留个联系方式嘛？

**Comment by huankong233** [comment]
> > 还是说发送成功了，但是Motrix内报24错误，那可能是下载未携带UA，造成返回了403错误
> 
> 发送成功了 在Motrix里报24错误有时报22错误 都是在Motrix里

方便在软件内截个图吗

![image](https://github.com/codehub666/94list/assets/49610758/8a15689e-f480-4153-b2a1-6be13ba4700d)

**Comment by huankong233** [comment]
错误列表

22
If HTTP response header was bad or unexpected.

24
If HTTP authorization failed.

问题多半就是因为下载的时候没有带UA

**Comment by qaz11ac** [comment]
> 错误列表
> 
> 22 如果 HTTP 响应标头错误或意外。
> 
> 24 如果 HTTP 授权失败。
> 
> 问题多半就是因为下载的时候没有带UA

那我该如何解决这个问题呢？

**Comment by qaz11ac** [comment]
> 错误列表
> 
> 22 如果 HTTP 响应标头错误或意外。
> 
> 24 如果 HTTP 授权失败。
> 
> 问题多半就是因为下载的时候没有带UA

LEVZnivO9V

**Comment by qaz11ac** [comment]
> 错误列表
> 
> 22 如果 HTTP 响应标头错误或意外。
> 
> 24 如果 HTTP 授权失败。
> 
> 问题多半就是因为下载的时候没有带UA

那我该如何解决这个问题呢

**Comment by huankong233** [comment]
> > 错误列表
> > 22 如果 HTTP 响应标头错误或意外。
> > 24 如果 HTTP 授权失败。
> > 问题多半就是因为下载的时候没有带UA
> 
> 那我该如何解决这个问题呢？

你怎么下载的，给个截图

**Comment by qaz11ac** [comment]
> > > 错误列表
> > > 22 如果 HTTP 响应标头错误或意外。
> > > 24 如果 HTTP 授权失败。
> > > 问题多半就是因为下载的时候没有带UA
> > 
> > 
> > 那我该如何解决这个问题呢？
> 
> 你怎么下载的，给个截图

问题现在可以下载了 下次再报错我再截图和你发那个截图 感谢大佬的回答 大佬方便加个q嘛？

**Comment by huankong233** [comment]
> > > > 错误列表
> > > > 22 如果 HTTP 响应标头错误或意外。
> > > > 24 如果 HTTP 授权失败。
> > > > 问题多半就是因为下载的时候没有带UA
> > > 
> > > 
> > > 那我该如何解决这个问题呢？
> > 
> > 
> > 你怎么下载的，给个截图
> > ![20230918220147](https://user-images.githubusercontent.com/144626630/268669165-fca44bfe-aa9b-42b4-927a-77cabddbb41d.png)
> 
> ![20230918220138](https://user-images.githubusercontent.com/144626630/268669146-c876308f-2d5b-4581-a9d3-2502fde36997.png)

右侧有详细信息，请点开

**Comment by huankong233** [comment]
> > > > 错误列表
> > > > 22 如果 HTTP 响应标头错误或意外。
> > > > 24 如果 HTTP 授权失败。
> > > > 问题多半就是因为下载的时候没有带UA
> > > 
> > > 
> > > 那我该如何解决这个问题呢？
> > 
> > 
> > 你怎么下载的，给个截图
> > ![20230918220147](https://user-images.githubusercontent.com/144626630/268669165-fca44bfe-aa9b-42b4-927a-77cabddbb41d.png)
> 
> ![20230918220138](https://user-images.githubusercontent.com/144626630/268669146-c876308f-2d5b-4581-a9d3-2502fde36997.png)

而且链接是有有效期的，大约是1.5h

**Comment by qaz11ac** [comment]
> > > > > 错误列表
> > > > > 22 如果 HTTP 响应标头错误或意外。
> > > > > 24 如果 HTTP 授权失败。
> > > > > 问题多半就是因为下载的时候没有带UA
> > > > 
> > > > 
> > > > 那我该如何解决这个问题呢？
> > > 
> > > 
> > > 你怎么下载的，给个截图
> > > ![20230918220147](https://user-images.githubusercontent.com/144626630/268669165-fca44bfe-aa9b-42b4-927a-77cabddbb41d.png)
> > 
> > 
> > ![20230918220138](https://user-images.githubusercontent.com/144626630/268669146-c876308f-2d5b-4581-a9d3-2502fde36997.png)
> 
> 而且链接是有有效期的，大约是1.5h

<img width="539" alt="1111" src="https://github.com/codehub666/94list/assets/144626630/16fe91ae-c725-4f28-8628-44f69d839699">


> > > > > 错误列表
> > > > > 22 如果 HTTP 响应标头错误或意外。
> > > > > 24 如果 HTTP 授权失败。
> > > > > 问题多半就是因为下载的时候没有带UA
> > > > 
> > > > 
> > > > 那我该如何解决这个问题呢？
> > > 
> > > 
> > > 你怎么下载的，给个截图
> > > ![20230918220147](https://user-images.githubusercontent.com/144626630/268669165-fca44bfe-aa9b-42b4-927a-77cabddbb41d.png)
> > 
> > 
> > ![20230918220138](https://user-images.githubusercontent.com/144626630/268669146-c876308f-2d5b-4581-a9d3-2502fde36997.png)
> 
> 而且链接是有有效期的，大约是1.5h

<img width="539" alt="1111" src="https://github.com/codehub666/94list/assets/144626630/aa277f7a-48ab-4805-ad0d-405c3756fee8">

**Comment by qaz11ac** [comment]
是这个截图吗

**Comment by qaz11ac** [comment]
大佬看看这是啥情况

**Comment by qaz11ac** [comment]
感谢感谢

**Comment by huankong233** [comment]
> 大佬看看这是啥情况

可能是没有ua吧，不是很清楚啊，你在浏览器里打开f12点network，然后发送给下载器，找最后一条jsonp的点开，然后截图一下

**Comment by qaz11ac** [comment]
> > 大佬看看这是啥情况
> 
> 可能是没有ua吧，不是很清楚啊，你在浏览器里打开f12点network，然后发送给下载器，找最后一条jsonp的点开，然后截图一下

<img width="648" alt="屏幕截图 2023-09-20 163337" src="https://github.com/codehub666/94list/assets/144626630/7a2e9686-3540-4397-b306-0c2f4f79f9c3">

**Comment by huankong233** [comment]
> > > 大佬看看这是啥情况
> > 
> > 
> > 可能是没有ua吧，不是很清楚啊，你在浏览器里打开f12点network，然后发送给下载器，找最后一条jsonp的点开，然后截图一下
> 
> <img alt="屏幕截图 2023-09-20 163337" width="648" src="https://user-images.githubusercontent.com/144626630/269219195-7a2e9686-3540-4397-b306-0c2f4f79f9c3.png">

这也不是我们这个项目，去他们那里开issues吧🤔，我解决不了
