### ISSUE TITLE
本地部署的一个网站提示错误-130是怎么回事

### ISSUE THREAD

**Issue by jerchen123** [codehub666/94list#32]
我之前租用的服务器到期了，找了个教程把自己电脑改造成临时个人的一个服务器了，搭建完后，开始到添加cookie都没问题了，但是解析连接时候提示错误-130 如图所示：可以帮忙看下是什么原因么，后台部署的也都没有问题
![image](https://github.com/codehub666/94list/assets/132264768/1869798a-9217-41bf-928f-58a90ad73f09)
![image](https://github.com/codehub666/94list/assets/132264768/cdf6a806-fe6b-4e61-979d-1661100db6ef)
![image](https://github.com/codehub666/94list/assets/132264768/612893ed-81d8-4229-99bb-306e2c04645a)

**Comment by jerchen123** [comment]
一开始以为是魔法上网的问题 但是关掉魔法上网还是不行 一直是错误代码-130

**Comment by codehub666** [comment]
链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因

**Comment by yuantuo666** [comment]
提取码错误，可以参见 https://github.com/yuantuo666/baiduwp-php/issues/217

**Comment by jerchen123** [comment]
> 提取码错误，可以参见 [yuantuo666/baiduwp-php#217](https://github.com/yuantuo666/baiduwp-php/issues/217)

不是很懂

**Comment by jerchen123** [comment]
> 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因

访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了

**Comment by yuantuo666** [comment]
> > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> 
> 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了

这个和IP无关，是你分享链接的提取码写错了，输入正确的提取码就可以下载。

**Comment by jerchen123** [comment]
> > > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> > 
> > 
> > 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了
> 
> 这个和IP无关，是你分享链接的提取码写错了，输入正确的提取码就可以下载。

我直接复制粘贴的，不可能会有错啊

**Comment by yuantuo666** [comment]
> > > > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> > > 
> > > 
> > > 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了
> > 
> > 
> > 这个和IP无关，是你分享链接的提取码写错了，输入正确的提取码就可以下载。
> 
> 我直接复制粘贴的，不可能会有错啊

方便分享出来吗，发送到这里

**Comment by jerchen123** [comment]
> > > > > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> > > > 
> > > > 
> > > > 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了
> > > 
> > > 
> > > 这个和IP无关，是你分享链接的提取码写错了，输入正确的提取码就可以下载。
> > 
> > 
> > 我直接复制粘贴的，不可能会有错啊
> 
> 方便分享出来吗，发送到这里

链接: https://pan.baidu.com/s/1p5KMvfyuPDoug7yuXobLbw?pwd=hejc 提取码: hejc 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by jerchen123** [comment]
我是本地用phpstudy部署的 没有租用服务器

**Comment by yuantuo666** [comment]
![image](https://github.com/codehub666/94list/assets/44130602/bb37e67d-05d6-4ac9-8e98-207d1c1d0a4e)
用演示站点测试没有问题

**Comment by jerchen123** [comment]
> ![image](https://user-images.githubusercontent.com/44130602/272471848-bb37e67d-05d6-4ac9-8e98-207d1c1d0a4e.png) 用演示站点测试没有问题

那我回去再试试，不行的话在找你吧，一般IP是公网IP应该都是可以正常使用的吧

**Comment by codehub666** [comment]
> > > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> > 
> > 
> > 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了
> 
> 这个和IP无关，是你分享链接的提取码写错了，输入正确的提取码就可以下载。
大佬过来观望了吖

**Comment by huankong233** [comment]
> 我之前租用的服务器到期了，找了个教程把自己电脑改造成临时个人的一个服务器了，搭建完后，开始到添加cookie都没问题了，但是解析连接时候提示错误-130 如图所示：可以帮忙看下是什么原因么，后台部署的也都没有问题 ![image](https://user-images.githubusercontent.com/132264768/271598366-1869798a-9217-41bf-928f-58a90ad73f09.png) ![image](https://user-images.githubusercontent.com/132264768/271599319-cdf6a806-fe6b-4e61-979d-1661100db6ef.png) ![image](https://user-images.githubusercontent.com/132264768/271599739-612893ed-81d8-4229-99bb-306e2c04645a.png)

获取列表的cookie请不要登陆！可能是黑号了！获取方法可以看 #36

**Comment by huankong233** [comment]
> > 链接有问题，可换个没登录过的浏览器访问这个分享链接查明原因
> 
> 访问都没有问题，我现在考虑的一个问题是不是我这个IP没有暴露在互联网的原因，也就是不是公网IP，但是我之前打电话开通了公网IP，这就不明白什么原因了

暴不暴露公网无关，暴露了反而其实不好，他如果反查发现了一部分特征可以把你这个ip封掉

**Comment by jerchen123** [comment]
你好，当前可能无法查看您的消息，请在您的电脑“砰”的一声后留言，我会尽快查看您的消息
