### ISSUE TITLE
请问如何直接通过API请求的方式跳过Auth请求

### ISSUE THREAD

**Issue by Markli66** [codehub666/94list#33]
问题是在PostMan想要测试接口的时候，随机请求一个接口，没有放置x-xsrf-token的情况下出现513错误和419错误，本来是自己想要新增一些API接口，学习一下API请求。不太了解。
目的是希望能也做一个油猴脚本来的。希望能够麻烦指点一下。我看到脚本本身就请求了一个几次后台其余都是内部中转其实本质上还是走分享链接获取参数，就是不知道PHP的框架下AUTH该如何解除

**Comment by Markli66** [comment]
主要就是我安装完成后，访问https://XXX域名/api/ 这个URL地址加上data: "type=get_info&version=" + version + "", 这个参数后没返回的是513
![image](https://github.com/codehub666/94list/assets/51303387/64be33ac-52c5-470d-84b9-50720570e685)

**Comment by codehub666** [comment]
演示接口有防火墙的，你获取不了，为了防止被盗取接口而存在。

**Comment by Markli66** [comment]
那请问如果想要使用类似的防火墙策略，去让一个接口不暴露或者类似防火墙的策略，能通过什么方式来呢？因为目前我也希望通过浏览器去书写一个类似的脚本来进行操作，本质上代码的逻辑是可以搞定的，就是串联后台接口的时候感觉中间缺少了一些东西。

**Comment by huankong233** [comment]
> 那请问如果想要使用类似的防火墙策略，去让一个接口不暴露或者类似防火墙的策略，能通过什么方式来呢？因为目前我也希望通过浏览器去书写一个类似的脚本来进行操作，本质上代码的逻辑是可以搞定的，就是串联后台接口的时候感觉中间缺少了一些东西。

在对发送的请求加上判断，加一个密码，或者套一个cloudflare
