### ISSUE TITLE
down_file文件时出现Trying to access array offset on value of type null in 

### ISSUE THREAD

**Issue by Markli66** [codehub666/94list#35]
![image](https://github.com/codehub666/94list/assets/51303387/04af2bb0-2da8-4e47-8a76-ddea894dc91c)

错误如图  
Notice: Trying to access array offset on value of type null in /www/wwwroot/XXX我的域名/function.php on line 443
{"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}

PHP版本为7.4  

类似的问题分别出现三种不同情况

Notice: Trying to access array offset on value of type null in /www/wwwroot/XXX我的域名/function.php on line 345
{"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}

Notice: Trying to access array offset on value of type null in /www/wwwroot/XX我的域名/function.php on line 500
{"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}

每次都是在修改获取列表账号的cookie:之后产生的变化

在页面上当出现500的时候是没办法渲染列表的，此时我的获取列表Cookie为空

当我获取列表的Cookie为代理账号的SVIPCK时出现message
: 
"未知错误代码：2"
success
: 
false  
不清楚什么原因。

**Comment by huankong233** [comment]
> ![image](https://user-images.githubusercontent.com/51303387/272970862-04af2bb0-2da8-4e47-8a76-ddea894dc91c.png)
> 
> 错误如图 Notice: Trying to access array offset on value of type null in /www/wwwroot/XXX我的域名/function.php on line 443 {"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}
> 
> PHP版本为7.4
> 
> 类似的问题分别出现三种不同情况
> 
> Notice: Trying to access array offset on value of type null in /www/wwwroot/XXX我的域名/function.php on line 345 {"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}
> 
> Notice: Trying to access array offset on value of type null in /www/wwwroot/XX我的域名/function.php on line 500 {"success":false,"message":"\u672a\u77e5\u9519\u8bef\u4ee3\u7801\uff1a"}
> 
> 每次都是在修改获取列表账号的cookie:之后产生的变化
> 
> 在页面上当出现500的时候是没办法渲染列表的，此时我的获取列表Cookie为空
> 
> 当我获取列表的Cookie为代理账号的SVIPCK时出现message : "未知错误代码：2" success : false 不清楚什么原因。

可能是网络环境不稳定导致的，几个都是在和百度服务器发送请求，然后请求失败了应该是
