### ISSUE TITLE
[个人问题]部署完以后页面有点小问题

### ISSUE THREAD

**Issue by XiaoGanCN** [codehub666/94list#36]
![Screenshot_20231015-235614](https://github.com/codehub666/94list/assets/76635216/d4348a48-afeb-4808-adc1-e424cdc03596)
我少装了什么但我又不知道（
求一位大佬指点一下，感激不尽

**Comment by haobad** [comment]
用电脑端操作试一下

**Comment by huankong233** [comment]
> ![Screenshot_20231015-235614](https://user-images.githubusercontent.com/76635216/275337922-d4348a48-afeb-4808-adc1-e424cdc03596.png) 我少装了什么但我又不知道（ 求一位大佬指点一下，感激不尽

上梯子，链接到cdn超时了
