### ISSUE TITLE
列表的账号状态一直显示待测试

### ISSUE THREAD

**Issue by UesugiErii1209** [codehub666/94list#37]
之前列表的账号状态是显示正常的，但是最近突然变成待测试了，请问是什么问题？麻烦看一下
![QQ图片20231021084527](https://github.com/codehub666/94list/assets/148557721/e3e9c894-0a8b-4be3-bedc-5fd63000743c)
![QQ图片20231021084533](https://github.com/codehub666/94list/assets/148557721/fe62b141-930c-49a9-8097-61008ed3c87e)

**Comment by haobad** [comment]
主页解析，然后获取高速链接后不就好了吗？

**Comment by codehub666** [comment]
获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题(被封？)导致无法获取。
据 @huankong233 所称现在获取列表是可以不关联cookie的了，可在函数库function.php获取列表函数get_list把cookie那段header(s)头删了试试看。

**Comment by huankong233** [comment]
> 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题(被封？)导致无法获取。 据 @huankong233 所称现在获取列表是可以不关联cookie的了，可在函数库function.php获取列表函数get_list把cookie那段header(s)头删了试试看。

不能删，删了就不能获取了，这个cookie的获取方法很简单，只需要打开隐私模式，然后打开 pan.baidu.com 然后复制cookie，注意！无需登陆！无需登陆！登陆了就会黑号

**Comment by codehub666** [comment]
> > 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题(被封？)导致无法获取。 据 @huankong233 所称现在获取列表是可以不关联cookie的了，可在函数库function.php获取列表函数get_list把cookie那段header(s)头删了试试看。
> 
> 不能删，删了就不能获取了，这个cookie的获取方法很简单，只需要打开隐私模式，然后打开 pan.baidu.com 然后复制cookie，注意！无需登陆！无需登陆！登陆了就会黑号

明白了，要有默认的cookie才行！

**Comment by UesugiErii1209** [comment]
> 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题（被封？）导致无法获取。 据 所称现在获取列表是可以不关联cookie的了，可在函数库函数.php获取列表函数get_list把cookie那段header（s）头删了试试看。

非常感谢解答，这边我自己尝试了下，估计是账号被封了

**Comment by UesugiErii1209** [comment]
> > 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题（被封？）导致无法获取。据  所称现在获取列表是可以不关联cookie的了，可在函数库函数.php获取列表函数get_list把cookie那段header（s）头删了试试看。
> 
> 不能删，删了就不能获取了，这个cookie的获取方法很简单，只需要打开隐私模式，然后打开 pan.baidu.com 然后复制cookie，注意！无需登陆！无需登陆！登陆了就会黑号

现在才看到哈哈哈。。。不过大佬请教一下，就是这个cookie不登陆的话，好像没办法正常获取，我给您看下我在隐私模式下打开pan.baidu.com复制的cookie
![image](https://github.com/codehub666/94list/assets/148557721/9bfb7b86-dd79-408b-a8c9-472e46552047)
![image](https://github.com/codehub666/94list/assets/148557721/da703b42-4ddd-43ac-b629-63941124a40e)
麻烦大佬指导下，谢谢

**Comment by huankong233** [comment]
> > > 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题（被封？）导致无法获取。据  所称现在获取列表是可以不关联cookie的了，可在函数库函数.php获取列表函数get_list把cookie那段header（s）头删了试试看。
> > 
> > 
> > 不能删，删了就不能获取了，这个cookie的获取方法很简单，只需要打开隐私模式，然后打开 pan.baidu.com 然后复制cookie，注意！无需登陆！无需登陆！登陆了就会黑号
> 
> 现在才看到哈哈哈。。。不过大佬请教一下，就是这个cookie不登陆的话，好像没办法正常获取，我给您看下我在隐私模式下打开pan.baidu.com复制的cookie ![image](https://user-images.githubusercontent.com/148557721/282286080-9bfb7b86-dd79-408b-a8c9-472e46552047.png) ![image](https://user-images.githubusercontent.com/148557721/282286115-da703b42-4ddd-43ac-b629-63941124a40e.png) 麻烦大佬指导下，谢谢

这个cookie是用来获取分享链接的列表的，不是用来获取下载链接的，这里的是用来获取下载链接的cookie

**Comment by UesugiErii1209** [comment]
> > > > 获取列表的cookie要在基础配置里面进行配置的。估计那个cookie出了什么问题（被封？）导致无法获取。据  所称现在获取列表是可以不关联cookie的了，可在函数库函数.php获取列表函数get_list把cookie那段header（s）头删了试试看。
> > > 
> > > 
> > > 不能删，删了就不能获取了，这个cookie的获取方法很简单，只需要打开隐私模式，然后打开 pan.baidu.com 然后复制cookie，注意！无需登陆！无需登陆！登陆了就会黑号
> > 
> > 
> > 现在才看到哈哈哈。。。不过大佬请教一下，就是这个cookie不登陆的话，好像没办法正常获取，我给您看下我在隐私模式下打开 pan.baidu.com 复制的cookie ![图像](https://user-images.githubusercontent.com/148557721/282286080-9bfb7b86-dd79-408b-a8c9-472e46552047.png) ![图像](https://user-images.githubusercontent.com/148557721/282286115-da703b42-4ddd-43ac-b629-63941124a40e.png) 麻烦大佬指导下，谢谢
> 
> 这个cookie是用来获取分享链接的列表的，不是用来获取下载链接的，这里的是用来获取下载链接的cookie

好的，感谢大佬的答复，我可以理解为隐私模式下获取的cookie是用于基础配置那一页面“获取列表账号的cookie”的，而需要登录上去的cookie是用于代理账号管理的对么？
