### ISSUE TITLE
功能的优化建议

### ISSUE THREAD

**Issue by haobad** [codehub666/94list#38]
目前搭建使用除了cookie获取使用有些突兀的失效外（当然我已经找到另外一种获取cookie的方法解决！），技术有限特别建议以下几个干货功能！
1.分享链接增加识别 ：分享链接不带&pwd=xxxx   的识别（尝试修改无果）
2.aira2推送发送6800端口失效（检测本机6800无占用，Motrix 16800端口推送正常）
3.解析文件夹功能是否如何开放？（目前还无头绪！）
4.解析文件夹进入下一层目录无返回上一次目录的按钮。。
5.增加手机端的识别优化，批量下载窗口大小及排序问题

**Comment by codehub666** [comment]
谢谢你的提议，不过现在我现在手头几个项目忙不过来暂时没法对94list进行更新，等找人进行对接项目或者等闲时在继续挖坑了。

**Comment by huankong233** [comment]
> 目前搭建使用除了cookie获取使用有些突兀的失效外（当然我已经找到另外一种获取cookie的方法解决！），技术有限特别建议以下几个干货功能！ 1.分享链接增加识别 ：分享链接不带&pwd=xxxx 的识别（尝试修改无果） 2.aira2推送发送6800端口失效（检测本机6800无占用，Motrix 16800端口推送正常） 3.解析文件夹功能是否如何开放？（目前还无头绪！） 4.解析文件夹进入下一层目录无返回上一次目录的按钮。。 5.增加手机端的识别优化，批量下载窗口大小及排序问题

文件夹解析，量大容易死号，一般没什么解析支持
第一项是什么意思，分享获取提取码吗，类似以前某download那种？

**Comment by huankong233** [comment]
> > 目前搭建使用除了cookie获取使用有些突兀的失效外（当然我已经找到另外一种获取cookie的方法解决！），技术有限特别建议以下几个干货功能！ 1.分享链接增加识别 ：分享链接不带&pwd=xxxx 的识别（尝试修改无果） 2.aira2推送发送6800端口失效（检测本机6800无占用，Motrix 16800端口推送正常） 3.解析文件夹功能是否如何开放？（目前还无头绪！） 4.解析文件夹进入下一层目录无返回上一次目录的按钮。。 5.增加手机端的识别优化，批量下载窗口大小及排序问题
> 
> 文件夹解析，量大容易死号，一般没什么解析支持 第一项是什么意思，分享获取提取码吗，类似以前某download那种？

如果是的话有法律风险

**Comment by haobad** [comment]
复制的时候没有使用自动填充分享码的分享链接识别。。并不涉及什么隐私

**Comment by huankong233** [comment]
> 复制的时候没有使用自动填充分享码的分享链接识别。。并不涉及什么隐私

这种的话可以给个示例吗

**Comment by haobad** [comment]
链接:https://pan.baidu.com/s/175-z87-izHvoZWZtWWEzHw 提取码:v3tj 复制这段内容后打开百度网盘手机App，操作更方便哦
这种后戳无&pwd=xxxx，需要手动输入
