### ISSUE TITLE
获取真实下载地址问题，错误码9019、2、112

### ISSUE THREAD

**Issue by fongYip** [codehub666/94list#39]
通过 /api/sharedownload 这个接口获取下载地址的时候，如果只是用 BDUSS 作为 Cookie 的话出现 9019 错误码。
然后我直接将整个 Cookie 贴上去了，就返回错误码 112。
之后我再把 timestamp 从 URL 参数中删掉了，错误码就是 2 了。
这该怎么解决？

**Comment by huankong233** [comment]
> 通过 /api/sharedownload 这个接口获取下载地址的时候，如果只是用 BDUSS 作为 Cookie 的话出现 9019 错误码。 然后我直接将整个 Cookie 贴上去了，就返回错误码 112。 之后我再把 timestamp 从 URL 参数中删掉了，错误码就是 2 了。 这该怎么解决？

https://github.com/yuantuo666/baiduwp-php/blob/master/app/Parse.php#L417-L450

完整原因看这里
