### ISSUE TITLE
连结不了数据库【已解决】

### ISSUE THREAD

**Issue by johnjohn-peace** [codehub666/94list#5]
我用macos 的MAMP 建了 localhost，也卡在数据库连结。
![1](https://github.com/codehub666/94list/assets/143049951/ab21a197-ed5c-45c1-82c7-7da596a5ccbb)

**Comment by codehub666** [comment]
大概率是PHP缺少Mysqli扩展
详细报错你可以按浏览器F12抓到错误回调

**Comment by johnjohn-peace** [comment]
错误回调我也沒看出什麼
![2](https://github.com/codehub666/94list/assets/143049951/77c59fc0-4c87-465e-a047-0e36891fca17)
mysqli我應該是有的，
![1](https://github.com/codehub666/94list/assets/143049951/8e9c6093-8a79-4f0d-84c7-f7ff00a39ae2)

**Comment by codehub666** [comment]
F12窗口->网络->点击连接数据库->回调一个新信息->点击新信息->回应->查看报错
如果实在不行联系QQ2797572563远程给你看一下

**Comment by johnjohn-peace** [comment]
試了一陣子，這樣對嗎？
![1](https://github.com/codehub666/94list/assets/143049951/42c034e0-cc2c-4d31-be80-40f969d4151a)

**Comment by codehub666** [comment]
在这个窗口你在点击"连接数据库"，他会发送一个包回来，看看那个包里面是什么报错

**Comment by johnjohn-peace** [comment]
發了api.php
![1](https://github.com/codehub666/94list/assets/143049951/ba7840f8-1fcb-4f5a-a104-591acdc1055b)
包里看了一下，沒找到報錯
![2](https://github.com/codehub666/94list/assets/143049951/65f6eb3b-c807-43dc-ad39-3c3b1dc1f56a)

**Comment by codehub666** [comment]
你部署的环境有问题啊，访问这个PHP文件不是解析代码，而是纯文本把整块代码输出出来了。

**Comment by codehub666** [comment]
你部署的环境有问题啊，请求这个PHP文件不是解析代码，而是纯文本把整块代码输出出来了。

**Comment by johnjohn-peace** [comment]
我成功连了数据库了，但获取列表数据又报错了，请问一下，有解决方法吗？
![2](https://github.com/codehub666/94list/assets/143049951/137fa315-2a84-4ad2-b18a-fa2a6b780a52)
![1](https://github.com/codehub666/94list/assets/143049951/be07084f-c2cc-4460-836c-43afac0c5a5b)

**Comment by jerchen123** [comment]
这个数据库连接是怎么回事么，我弄的时候也是连接不上 准备第二天再弄的时候就自动连接上了，有大佬解释下具体原因么

**Comment by jerchen123** [comment]
我用的宝塔自动创建的数据库，就是连接不上，控制台回调的也是php.API,但是第二天再弄的时候自动就连上数据库了

**Comment by jerchen123** [comment]
有知道原因的大佬麻烦解答一下，我的服务器快到期了 换服务器在经历一次的话脑仁就该炸了

**Comment by PTrustMe** [comment]
请问一下连接数据库时候提示：无权限配置数据库信息。是什么原因呢？

**Comment by jerchen123** [comment]
谢啦，SB！！！
