### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by koy1619** [codehub666/94list#6]
务器版本
php-8.0.0   phpinfo 显示有mysqli扩展
mysql5.7
nginx-1.20.1
![截图](https://github.com/codehub666/94list/assets/4476308/6e776e4d-f4f7-4255-9a2b-1f694d5a64cb)

**Comment by koy1619** [comment]
![微信截图_20230828111807](https://github.com/codehub666/94list/assets/4476308/045b3089-9249-4c9c-85ae-ec61cd1c92b4)
![微信截图_20230828111743](https://github.com/codehub666/94list/assets/4476308/9d634460-2912-46bc-a715-75134605561a)

**Comment by codehub666** [comment]
看你的回调直接把function的函数库打印出来了，使用php7.4试试看吧。

**Comment by codehub666** [comment]
看你的回调直接把api.php的内容打印出来了，并没有正确运行代码。
可能是环境兼容问题，建议更换PHP7.4尝试。

**Comment by koy1619** [comment]
phpinfo我也是放在同级目录都可以运行出来啊

**Comment by koy1619** [comment]
> 看你的回调直接把api.php的内容打印出来了，并没有正确运行代码。 可能是环境兼容问题，建议更换PHP7.4尝试。

我换成php-7.4.30，直接在根目录 用socket跑，目录也777了，依旧一样的报错，这个到底是什么问题
/usr/local/php-7.4.30/bin/php -S 0.0.0.0:8888

**Comment by codehub666** [comment]
已经解决
