### ISSUE TITLE
建议一个

### ISSUE THREAD

**Issue by 1Q23LYC45** [codehub666/94list#7]
关于网页版源码的一个建议。希望支持SQLite3，这样就可以傻瓜式搭建了。平时极少用MySQL，兼容性和易用性不如SQLite，总是各种权限不足，整了半天才安装上。SQLite只要有个PHP就支持，MySQL需要另装软件

**Comment by codehub666** [comment]
没时间整两个数据库的调配，两者二选一MySql对于我好上手一点。SQLite是在文件内进行嵌入式存储，使得项目以后如果扩展并发记录下载次数功能可能不友好(为用户隐私安全不会记录解析链接)，包括其他并发访问请求功能，在这种并发下大数据存储轻量级SQLite根本不适合，别让它简易但是需要看需求而定。

**Comment by codehub666** [comment]
没时间整两个数据库的调配，两者二选一MySql对于我好上手一点。SQLite是在文件内进行嵌入式存储，使得项目以后如果扩展并发记录下载次数功能可能不友好(为用户隐私安全不会记录解析链接)，包括其他并发访问请求功能，在这种并发下大数据存储轻量级SQLite根本不适合，别看它简易而是看需求而定。

**Comment by 1Q23LYC45** [comment]
嗯。对我来说MySQL上手有点难，如果不用PHPMyAdmin根本不能进行任何操作（各种权限不足），SQLite基本是傻瓜式一键完成，还有SQLiteEditorAPP支持可视化管理。我认为建博客SQLite是挺好的，目前自用的是Z-BlogPHP和Typecho，这两个博客软件都支持SQLite。

**Comment by 1Q23LYC45** [comment]
有什么管理MYSQL的软件推荐吗

**Comment by codehub666** [comment]
> 有什么管理MYSQL的软件推荐吗

dbforge studio for mysql
