### ISSUE TITLE
能否支持解析普通速度的下载链接

### ISSUE THREAD

**Issue by ddpang** [codehub666/94list#8]
像我的需求是,不去客户端下载,小文件其实对下载速度没要求的.
大文件就正常开svip嘛.

**Comment by codehub666** [comment]
是可以识别普通账号的，普通账号解析的自然就是普通链接。不过速度EMMM.....

**Comment by ddpang** [comment]
感谢回复。我是普通百度账号，但并未获取到普通速度链接；我的操作步骤和相关截图如下：
1.本地网盘点击就是加速启动，并未获取到普通链接。而是提示脚本维护，需要到web页操作。网页截图如下
![image](https://github.com/codehub666/94list/assets/40516116/78f27dbd-3295-49b4-86e0-9c12e570195f)
2.在web页提示账号不足，换个时间段再访问
![image](https://github.com/codehub666/94list/assets/40516116/764b24b0-d0f6-45a8-8b2f-efffd43cc248)

**Comment by codehub666** [comment]
> 感谢回复。我是普通百度账号，但并未获取到普通速度链接；我的操作步骤和相关截图如下： 1.本地网盘点击就是加速启动，并未获取到普通链接。而是提示脚本维护，需要到web页操作。网页截图如下 ![image](https://user-images.githubusercontent.com/40516116/263964518-78f27dbd-3295-49b4-86e0-9c12e570195f.png) 2.在web页提示账号不足，换个时间段再访问 ![image](https://user-images.githubusercontent.com/40516116/263965382-764b24b0-d0f6-45a8-8b2f-efffd43cc248.png)

你这个是就是加速那边的业务了，不在我开源项目管辖内。
用我的演示站点吧:[https://www.uy5.net/discuss/19115.html](https://www.uy5.net/discuss/19115.html)

**Comment by ddpang** [comment]
原来是来到了克隆窝这边的开源项目。。。误打误撞发现一个宝藏平台，赞
