### ISSUE TITLE
显示Json解析错误【已解决】

### ISSUE THREAD

**Issue by jerchen123** [codehub666/94list#9]
页面显示json解析错误怎么回事
![image](https://github.com/codehub666/94list/assets/132264768/06a927eb-6a11-4a20-acdc-35115f89299b)

**Comment by jerchen123** [comment]
有没有大佬出来帮忙解决一下 谢谢

**Comment by jerchen123** [comment]
大佬能不能出一个部署后的配置教程

**Comment by jerchen123** [comment]
![image](https://github.com/codehub666/94list/assets/132264768/829f41ce-6370-4c30-8b40-f9ca66331e4c)
控制台提示这个

**Comment by codehub666** [comment]
正确获取网页cookie的方式
![QQ截图20230829201944](https://github.com/codehub666/94list/assets/81606392/50982b31-4040-4a71-bab6-21f7119e48b4)

**Comment by jerchen123** [comment]
不好意思，请忽略上面的自动回复，我的账号被借出去过，不清楚被设置了什么，如果您知道的话，可以告诉我一下怎么取消掉这个自动回复呢

**Comment by jerchen123** [comment]
cookie问题解决了，谢谢
![image](https://github.com/codehub666/94list/assets/132264768/d6e672b5-d2c7-49f5-abb4-150711dce8e8)
解析链接解析不出来是什么原因呢

**Comment by codehub666** [comment]
> cookie问题解决了，谢谢 ![image](https://user-images.githubusercontent.com/132264768/264031769-d6e672b5-d2c7-49f5-abb4-150711dce8e8.png) 解析链接解析不出来是什么原因呢

基础设置的列表cookie也要设置一下。因为你是管理员身份，所以他回调的是php报错，需要在控制台回调查看报错的。

**Comment by jerchen123** [comment]
基础设置的列表cookie也是和代理账号的cookie一样的么,这个我也填写了一样的，但是还是解析不出连接。还有几个问题就是1，代理账号管理的地方账号状态一直显示待测试是怎么回事 2，如果代理账号里有两个账号的cookie，是不是基础设置的列表cookie也要都填上两个账号的cookie信息。3，如果代理账号2个及以上，其中有SVIP的 有普通用户的，是优先哪个账号进行代理的。

**Comment by jerchen123** [comment]
![image](https://github.com/codehub666/94list/assets/132264768/ea5b0776-22d0-48ed-86fb-501ac185e148)

**Comment by jerchen123** [comment]
![image](https://github.com/codehub666/94list/assets/132264768/6141958c-77e2-4857-9d41-103125e8fc4d)
控制台提示的是这个

**Comment by codehub666** [comment]
不是这么看的，你要看“网络”那边的。看一下通讯回调的是什么内容。

**Comment by jerchen123** [comment]
![image](https://github.com/codehub666/94list/assets/132264768/3c723e5c-aa1d-4962-86bf-2e3cb241e995)
我是纯粹半吊子一个，真的不清楚怎么回事，就懂一些前端代码  数据库什么的真的搞不太懂

**Comment by codehub666** [comment]
+Q2797572563给你远程看看怎么回事

**Comment by jerchen123** [comment]
申请了 您那边通过一下

**Comment by codehub666** [comment]
解决了，楼主获取cookie方式有问题，列表cookie不合格

**Comment by codehub666** [comment]
是cookie的符号和表单发生提交冲突
